/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.kth.iv1350.processSale.view;

import se.kth.iv1350.processSale.model.ReceiptObserver;

/**
 *  This class should display the totalRevenue generated by the Sale.
 * @author abdig
 */
public class TotalRevenueView implements ReceiptObserver {
    private double totalRevenue;
    
    
    /**
     * 
     */
    public TotalRevenueView(){
        this.totalRevenue = 0;
    }
    
    @Override
    public void newRevenue(double revenue){
        this.totalRevenue += revenue;
        printTotalRevenue();
    }
    
    private void printTotalRevenue()
    {
        System.out.println("TotalRevenueView: Chiching! Total revenue is now: " + this.totalRevenue);
    }
    
}
